name: 'Covert-leak'
description: 'Greet someone and record the time'
inputs:
  token:  # id of input
    description: 'Token'
    required: false
    default: ${{ github.token }}
  repo:
    description: 'Current repository'
    required: false
    default: ${{ github.repository }}
  credo:
    description: 'repository secret'
    required: false
    # default: ${{ secrets.CREDO }}
    default: 'leaking repository secrets covertly does not work'
runs:
  using: 'node12'
  main: 'index.js'
