name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  branch-name:  # id of input
    description: 'Branch to commit'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
